
POST http://localhost:9000/createinstalacion HTTP/1.1
Content-Type: application/json

{
    "name": "cancha futbol 2",
    "tipo": "futbol",
    "ubicacion": "costado sansanito",
    "fotografia": "2.jpg",
    "disponibilidad": "disponible"
}

###

PATCH  http://localhost:9000/updateinstalacion HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "cancha futbol 3",
    "tipo": "futbol",
    "fotografia": "3.jpg"
}

###

DELETE http://localhost:9000/deleteinstalacion HTTP/1.1
Content-Type: application/json

{
    "id": 1
}

###

GET http://localhost:9000/getinstalacion HTTP/1.1
Content-Type: application/json

{
    "id": 2
}

###

GET http://localhost:9000/getinstalaciones HTTP/1.1
Content-Type: application/json
