
POST http://localhost:9000/createreserva HTTP/1.1
Content-Type: application/json

{
    "fecha": "mañana",
    "bloque": "13-14",
    "estado": "reservada",
    "userId": 3,
    "instalacionId": 2,
    "instalacion": "Nombre de instalacion"
}

###

PATCH  http://localhost:9000/updatereserva HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "fecha": "pasado mañana",
    "bloque": "13-14",
    "estado": "reservada"
}

###

DELETE http://localhost:9000/deletereserva/2 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:9000/getreserva/2 HTTP/1.1
Content-Type: application/json


###

GET http://localhost:9000/getreservas HTTP/1.1
Content-Type: application/json


###

GET http://localhost:9000/getreservasbyuser/3 HTTP/1.1
Content-Type: application/json

