
POST http://localhost:9000/createinstalacion HTTP/1.1
Content-Type: application/json

{
    "username": "Franzisko",
    "password": "myPass"
}

PATCH  http://localhost:9000/updateinstalacion HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "username": "Chris",
    "password": "12345",
    "email": "chris.riquelme@usm.cl"
}

DELETE http://localhost:9000/deleteinstalacion HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "username": "fernando",
    "password": "1234",
    "email": "fernando.carrasco@usm.cl"
}

GET http://localhost:9000/getinstalacion HTTP/1.1
Content-Type: application/json

{
    "id": 1
}