
POST http://localhost:9000/createinstalacion HTTP/1.1
Content-Type: application/json

{
    "name": "Cancha Basketball",
    "tipo": "Basketball",
    "ubicacion": "Al costado del sansanito, frente al gimnasio.",
    "fotografia": "4.jpg",
    "disponibilidad": "disponible"
}

###

PATCH  http://localhost:9000/updateinstalacion HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "cancha futbol 3",
    "tipo": "futbol",
    "fotografia": "3.jpg"
}

###

DELETE http://localhost:9000/deleteinstalacion/2 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:9000/getinstalacion HTTP/1.1
Content-Type: application/json


###

GET http://localhost:9000/getinstalaciones HTTP/1.1
Content-Type: application/json
